// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPwq07rxlnW5s9pZpu5HhDY_YSvSmyV6E',
    appId: '1:516427757579:web:40446bdfdec2e379766f0e',
    messagingSenderId: '516427757579',
    projectId: 'chatapp-dd199',
    authDomain: 'chatapp-dd199.firebaseapp.com',
    storageBucket: 'chatapp-dd199.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4gyiAKroHSQALp_5I3P9DbZP6Cr9Q9gE',
    appId: '1:516427757579:android:a01d0a3fe9158b7d766f0e',
    messagingSenderId: '516427757579',
    projectId: 'chatapp-dd199',
    storageBucket: 'chatapp-dd199.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIVp2M66ZW7mt0XFdGAO9uyD81OGbTLK0',
    appId: '1:516427757579:ios:011e8621585d90cd766f0e',
    messagingSenderId: '516427757579',
    projectId: 'chatapp-dd199',
    storageBucket: 'chatapp-dd199.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIVp2M66ZW7mt0XFdGAO9uyD81OGbTLK0',
    appId: '1:516427757579:ios:011e8621585d90cd766f0e',
    messagingSenderId: '516427757579',
    projectId: 'chatapp-dd199',
    storageBucket: 'chatapp-dd199.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPwq07rxlnW5s9pZpu5HhDY_YSvSmyV6E',
    appId: '1:516427757579:web:15f0bf49ef3579e7766f0e',
    messagingSenderId: '516427757579',
    projectId: 'chatapp-dd199',
    authDomain: 'chatapp-dd199.firebaseapp.com',
    storageBucket: 'chatapp-dd199.appspot.com',
  );
}
